[package]
name = "vrrb_http"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
mempool = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = "2.3"
vrrb_core = { workspace = true }

[dev-dependencies]
wiremock = "0.5"
