[package]
name = "internal_rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { workspace = true }
platform = { workspace = true }
serde = { workspace = true }
service_config = { workspace = true }
