[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
bytebuffer = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
ritelinked = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
state = { workspace = true }
vrrb_core = { workspace = true }
