[package]
name = "wallet"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "wallet"
path = "src/lib.rs"

[[test]]
name = "wallet-rpc-tests"
path = "tests/wallet_rpc_tests.rs"

[dependencies]
chrono = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true }
primitives = { workspace = true }
rand = { workspace = true }
ritelinked = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
storage = { workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
utils = { workspace = true }
uuid = { workspace = true }
vrrb_core = { workspace = true }
vrrb_rpc = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
