[package]
name = "versa_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
mempool = { workspace = true }
vrrb_core = { workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
wiremock = { workspace = true }
url = { workspace = true }