[package]
name = "wasm_cli"
description = "Versatus developer CLI and WASM runtime"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "versa-wasm"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
bonsaidb = { version = "*", features = ["local"] }
bonsaidb-core = "0.5.0"
bonsaidb-local = "0.5.0"
clap = { workspace = true }
ethereum-types = { workspace = true }
ethnum = "1.5.0"
primitives = { workspace = true }
telemetry = { workspace = true }
tokio = { workspace = true }
wasm_loader = { workspace = true }
wasm_runtime = { workspace = true }
wasmer = { workspace = true }
wasmer-wasix = { workspace = true }
wasmer-wasix-types = { workspace = true }
web3_pkg = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
versatus-rust = { git = "https://github.com/versatus/versatus-rust"}
