[package]
name = "wasm_cli"
description = "VRRB developer CLI and WASM runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bonsaidb = { workspace = true }
bonsaidb-core = { workspace = true }
bonsaidb-local = { workspace = true }
clap = { workspace = true }
wasmer = { workspace = true }
wasmer-wasix = { workspace = true }
wasmer-wasix-types = { workspace = true }
wasm_loader = { workspace = true }
wasm_runtime = { workspace = true }
telemetry = { workspace = true }
ethereum-types = { workspace = true }
serde = { workspace = true }
primitives = { workspace = true }
secp256k1 = { workspace = true }
versatus-rust = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
ethnum ={ workspace = true }