[profile.release]
opt-level = 3
lto = "fat"

[workspace]
members = [
    "primitives",
    "block",
    "blockchain",
    "claim",
    "miner",
    "state",
    "txn",
    "wallet",
    "events",
    "ev_mem_pool",
    "commands",
    "mempool",
    "messages",
    "vrrb_lib",
    "vrrb_cli",
    "vrrb_gui",
    "vrrb_vrf",
    "network",
    "node",
    "verifiable",
    "ledger",
    "accountable",
    "ownable",
    "noncing",
    "updateable",
    "quorum",
    "state_trie",
    "lrdb",
    "lr_trie",
    "tx_trie",
    "dkg_engine",
    "telemetry",
]
