[package]
name = "vrrb"
description = "Rust implementation of VRRB"
version = "0.1.0"
authors = ["VRRB Labs <info@vrrb.io>"]
edition = "2021"
readme = "README.md"
[metadata.cargo-udeps.ignore]

[profile.release]
opt-level = 3
lto = "fat"

[[bin]]
name = "vrrb"
path = "crates/cli/src/main.rs"

[dependencies]
tokio = { version = "1.21.0", features = ["full"] }
telemetry = { path = "crates/telemetry" }
commands = { path = "crates/commands" }
cli = { path = "crates/cli" }
anyhow = "1.0.64"

[dev-dependencies.cargo-husky]
version = "1"
features = ["user-hooks"]

[package.metadata.cargo-udeps.ignore]
normal = ["cargo-husky"]
development = ["cargo-husky"]

[workspace]
members = [
    "crates/primitives",
    "crates/vrrb_core",
    "crates/cli",
    "crates/vrrb_config",
    "crates/vrrb_rpc",
    "crates/block",
    "crates/blockchain",
    "crates/claim",
    "crates/miner",
    "crates/state",
    "crates/txn",
    "crates/wallet",
    "crates/events",
    "crates/ev_mem_pool",
    "crates/commands",
    "crates/mempool",
    "crates/messages",
    "crates/vrrb_lib",
    "crates/vrrb_cli",
    "crates/vrrb_gui",
    "crates/vrrb_vrf",
    "crates/network",
    "crates/node",
    "crates/storage",
    "crates/syncing",
    "crates/verifiable",
    "crates/ledger",
    "crates/accountable",
    "crates/ownable",
    "crates/noncing",
    "crates/updateable",
    "crates/quorum",
    "crates/lrdb",
    "crates/lr_trie",
    "crates/dkg_engine",
    "crates/telemetry",
    "crates/signer",
]
