
[package]
name = "vrrb"
description = "Rust implementation of VRRB"
version = "0.1.0"
authors = ["VRRB Labs <info@vrrb.io>"]
edition = "2021"
readme = "README.md"

[profile.release]
opt-level = 3
lto = "fat"

[[bin]]
name = "vrrb"
path = "node/service/src/main.rs"

[dependencies]
tokio = { version = "1.21.0", features = ["full"] }
telemetry = { path = "telemetry" }
node_cli = { path = "node/cli" }
service = { path = "node/service" }

[workspace]
members = [
    "primitives",
    "block",
    "blockchain",
    "claim",
    "miner",
    "state",
    "txn",
    "wallet",
    "events",
    "ev_mem_pool",
    "commands",
    "mempool",
    "messages",
    "vrrb_lib",
    "vrrb_cli",
    "vrrb_gui",
    "vrrb_vrf",
    "network",
    "node/cli",
    "node/service",
    "node/core",
    "verifiable",
    "ledger",
    "accountable",
    "ownable",
    "noncing",
    "updateable",
    "quorum",
    "state_trie",
    "lrdb",
    "lr_trie",
    "tx_trie",
    "dkg_engine",
    "telemetry",
    "signer"
]
