[workspace]
members = [
    "block",
    "blockchain",
    "claim",
    "miner",
    "state",
    "txn",
    "wallet",
    "events",
    "commands",
    "gossipsub",
    "messages",
    "gd_udp",
    "vrrb_lib",
    "vrrb_tui",
    "vrrb_cli",
    "vrrb_gui",
    "network",
    "node",
    "verifiable",
    "ledger",
    "accountable",
    "ownable",
    "noncing",
    "updateable",
    "vrrb_dht",
    "claim_concept",
    "simulation",
]