[profile.release]
opt-level = 3
lto = "fat"

[workspace]
members = [
    "block",
    "blockchain",
    "claim",
    "miner",
    "state",
    "txn",
    "wallet",
    "events",
    "commands",
    "mempool",
    "messages",
    "vrrb_lib",
    "vrrb_tui",
    "vrrb_cli",
    "vrrb_gui",
    "network",
    "node",
    "verifiable",
    "ledger",
    "accountable",
    "ownable",
    "noncing",
    "updateable",
    "quorum",
]

exclude = ["claim_concept"]
