[package]
name = "vrrb_core"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
telemetry = { path = "../telemetry" }
primitives = { path = "../primitives" }
anyhow = "1.0.65"
thiserror = "1.0.37"
ritelinked = { version = "0.3.2", features = ['serde'] }
sha256 = "1.1.1"
serde_json = "1.0.64"
serde = { version = "1.0.144", features = ["derive"] }
hex = "0.4.3"
secp256k1 = { version = "0.25.0", features = [
    "rand",
    "bitcoin_hashes",
    "global-context",
] }
bytebuffer = "0.2.1"
uuid = { version = "0.8.0", features = ["serde", "v4"] }
lru_time_cache = "0.11.11"
hbbft = { git = "https://github.com/vrrb-io/hbbft", branch = "master" }
rand = "0.8.5"
bincode = "1.3.3"
storage = { path = "../storage" }
udp2p = { git = "https://github.com/ASmithOWL/udp2p" }
sha2 = "0.10.2"
chrono = "0.4.23"
async-trait = "0.1.58"
theater = { git = "https://github.com/vrrb-io/theater" }
utils = { path = "../utils" }
