[package]
name = "vrrb_core"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
bs58 = "0.4"
chrono = { workspace = true }
cuckoofilter = { workspace = true }
ethereum-types = { workspace = true }
hbbft = { workspace = true }
hex = { workspace = true }
lru_time_cache = { workspace = true }
primitives = { workspace = true }
rand = { workspace = true }
ring = "0.16"
ritelinked = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
utils = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
