[package]
name = "wasm_loader"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
telemetry = { workspace = true }
wasmer = { workspace = true }
wasmparser = { workspace = true }
derive_builder = { workspace = true }
anyhow = { workspace = true }
env_logger = "0.10"
test-log = "0.2"
