[package]
name = "wasm_loader"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
telemetry = { workspace = true }
wasmer = { workspace = true }
wasmparser = "0.107"
derive_builder = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
test-log = "0.2"
