[package]
name = "storage"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
primitives = { workspace = true }


[dev-dependencies]
serial_test = { workspace = true }
