[package]
name = "storage"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
vrrbdb = { workspace = true }
storage_utils = { workspace = true }
ethereum-types = { workspace = true }
integral-db = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
