[package]
name = "storage"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
primitives = { workspace = true }
ritelinked = { workspace = true }
sha256 = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
lrdb = { workspace = true }
mempool = { workspace = true }
reward = { workspace = true }
lr_trie = { workspace = true }
vrrb_core = { workspace = true }
telemetry = { workspace = true }
patriecia = { workspace = true }
rand = { workspace = true }
derive_builder = { workspace = true }
rocksdb = { workspace = true }
left-right = { workspace = true }
keccak-hash = { workspace = true }
parking_lot = { workspace = true }
rlp = { workspace = true }
bincode = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
criterion = { workspace = true }
ethereum-types = { workspace = true }
uuid = { workspace = true }
