[package]
name = "storage"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lrdb = { workspace = true }
lr_trie = { workspace = true }
storage_utils = { workspace = true }
state = { workspace = true }
