[package]
name = "block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = {version = "0.20.2", features = ["rand"]}
sha256 = "1.0.2"
rand = {version = "0.6", features = ["std"]}
uuid = { version = "0.8.0", features = ["serde", "v4"] }
bytebuffer = "0.2.1"
chrono = "0.4.20"
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
blake3 = "0.3.8"
bip39 = "1.0.1"
<<<<<<< HEAD
pickledb = "0.4.1"
=======
pickledb = "0.5.1"
libp2p = "0.41.1"
>>>>>>> b1bb0da (Fixed most of cargo audit issues.)
futures = "0.3.1"
async-std = { version = "1", features = ["attributes", "tokio1"] }
tokio = {version = "1.12.0", features = ["full"]}
env_logger = "0.8.1"
hex = "*"
itertools = "0.10.1"
crossterm = { version = "0.19", features = [ "serde" ] }
tui = { version = "0.14", default-features = false, features = ['crossterm', 'serde'] }
thiserror = "1.0"
ctrlc = "3.2.0"
simplelog = "0.10.0"
log = "0.4.14"
ritelinked = {version = "0.3.2", features = [ 'serde' ]}
claim = { path = "../claim" }
reward = { path = "../reward" }
txn = { path = "../txn" }
verifiable = { path = "../verifiable" }
noncing = { path = "../noncing" }
state = { path = "../state" }
accountable = { path = "../accountable" }
