[package]
name = "platform"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bitmask-enum = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uname-rs = "0.1.1"
