[package]
name = "platform"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[example]]
name = "cgroup_stats"
path = "../../examples/cgroup_stats.rs"

[dependencies]
anyhow = { workspace = true }
bitmask-enum = { workspace = true }
nix = { version = "0.27", features = ["feature"] }
serde = { workspace = true }
thiserror = { workspace = true }
