[package]
name = "cli"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Example of customizing binaries in Cargo.toml.

[lib]
name = "cli"
path = "src/lib.rs"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
node = { path = "../node" }
vrrb_config = { path = "../vrrb_config" }
primitives = { path = "../primitives" }
telemetry = { path = "../telemetry" }
storage = { path = "../storage" }
anyhow = "1.0.64"
tracing = "0.1.36"
thiserror = "1.0.34"
uuid = { version = "0.8.0", features = ["serde", "v4"] }
vrrb_core = { path = "../vrrb_core" }

[dev-dependencies]
assert_cmd = "2.0.4"
