[package]
name = "vrrbdb"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
sha2 = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
vrrb_core = { workspace = true }
primitives = { workspace = true }
patriecia = { workspace = true }
parking_lot = { workspace = true }
bincode = { workspace = true }
storage_utils = { workspace = true }
serde_json = { workspace = true }
telemetry = { workspace = true }
ethereum-types = { workspace = true }
integral-db = { workspace = true }
hex = { workspace = true }
block = { workspace = true }
ritelinked = { workspace = true }
rocksdb = "0.19"

[dev-dependencies]
rand = { workspace = true }
serial_test = { workspace = true }
