[package]
name = "state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ritelinked = { workspace = true }
sha256 = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
lrdb = { workspace = true }
mempool = { workspace = true }
reward = { workspace = true }
lr_trie = { workspace = true }
primitives = { workspace = true }
vrrb_core = { workspace = true }
telemetry = { workspace = true }
patriecia = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
derive_builder = { workspace = true }
rocksdb = { workspace = true }
