[package]
name = "signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false

[dependencies]
hbbft = {git = "https://github.com/vrrb-io/hbbft", branch = "master"} 
thiserror = "1.0.32"
serde = "1.0.144"
primitives = { path = "../primitives" }
node = { path = "../node" }
dkg_engine = { path = "../dkg_engine" }
