[package]
name = "primitives"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hbbft = { workspace = true }
hex = { workspace = true }
kademlia-dht = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
sha3 = "0.10"
thiserror = { workspace = true }
