[package]
name = "primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
serde = { version = "1.0.145", features = ["derive"] }
secp256k1 = { version = "0.24.0", features = ["rand", "serde"] }