[package]
name = "dkg_engine"
description = "Distributed Key Generator, currently deprecated"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
hbbft = { workspace = true }
hex = { workspace = true }
primitives = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
vrrb_config = { workspace = true }
vrrb_core = { workspace = true }
