[package]
name = "job_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadfin = "0.1.1"
num_cpus = "1.14.0"
once_cell = "1.16.0"
primitives={path="../primitives"}