[package]
name = "job_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.14.0"
once_cell = "1.16.0"
primitives={path="../primitives"}
job_pool={"path"="../job_pool"}
vrrb_core = { path = "../vrrb_core" }
rand = "0.8.5"
thiserror = "1.0.32"