[package]
name = "node"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
block = { workspace = true }
bulldag = { workspace = true }
bytes = "1.3"
chrono = { workspace = true }
crossbeam-channel = { workspace = true }
derive_builder = { workspace = true }
dyswarm = { workspace = true }
ethereum-types = { workspace = true }
events = { workspace = true }
hbbft = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
integral-db = { workspace = true }
jsonrpsee = { workspace = true }
kademlia-dht = { workspace = true }
lazy_static = { workspace = true }
mempool = { workspace = true }
messr = { workspace = true }
miner = { workspace = true }
patriecia = { workspace = true }
primitives = { workspace = true }
quorum = { workspace = true }
rand = { workspace = true }
raptorq = "1.7"
rayon = { workspace = true }
reward = { workspace = true }
ritelinked = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sha256 = { workspace = true }
signer = { workspace = true }
storage = { workspace = true }
telemetry = { workspace = true }
theater = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["rt"] }
utils = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
vrrb_config = { workspace = true }
vrrb_core = { workspace = true }
vrrb_http = { workspace = true }
vrrb_rpc = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
serial_test = { workspace = true }
