[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { path = "../primitives" }
block = { path = "../block" }
vrrb_core = { path = "../vrrb_core" }
telemetry = { path = "../telemetry" }
vrrb_config = { path = "../vrrb_config" }
commands = { path = "../commands" }
network = { path = "../network" }
messages = { path = "../messages" }
lr_trie = { path = "../lr_trie" }
storage = { path = "../storage" }
miner = { path = "../miner" }
wallet = { path = "../wallet" }
state = { path = "../state" }
validator = { path = "../validator" }
events = { path = "../events" }
reward = { path = "../reward" }
blockchain = { path = "../blockchain" }
vrrb_rpc = { path = "../vrrb_rpc" }
patriecia = { git = "https://github.com/vrrb-io/patriecia" }
trecho = { git = "https://github.com/vrrb-io/trecho" }
udp2p = { git = "https://github.com/ASmithOWL/udp2p" }
secp256k1 = { version = "0.20.2", features = ["rand"] }
sha256 = "1.0.2"
rand = { version = "0.6", features = ["std"] }
bytebuffer = "0.2.1"
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
blake3 = "0.3.8"
pickledb = "0.5.1"
tokio = { version = "1.12.0", features = ["full"] }
hex = "*"
thiserror = "1.0"
ritelinked = { version = "0.3.2", features = ['serde'] }
bincode = "1.3.3"
uuid = { version = "0.8", features = ["serde", "v4"] }
tracing = "0.1.36"
poem = "1.3.43"
public-ip = "0.2.2"
anyhow = "1.0.65"
async-trait = "0.1.58"
