[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { workspace = true }
block = { workspace = true }
vrrb_core = { workspace = true }
telemetry = { workspace = true }
vrrb_config = { workspace = true }
network = { workspace = true }
lr_trie = { workspace = true }
storage = { workspace = true }
wallet = { workspace = true }
validator = { workspace = true }
reward = { workspace = true }
vrrb_rpc = { workspace = true }
patriecia = { workspace = true }
trecho = { workspace = true }
udp2p = { workspace = true }
secp256k1 = { workspace = true }
sha256 = { workspace = true }
rand = { workspace = true }
bytebuffer = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
blake3 = { workspace = true }
pickledb = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
ritelinked = { workspace = true }
bincode = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
poem = { workspace = true }
public-ip = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
derive_builder = { workspace = true }
jsonrpsee = { workspace = true }
bytes = { workspace = true }
theater = { workspace = true }
kademlia-dht = { workspace = true }
dkg_engine = { workspace = true }
hbbft = { workspace = true }
mempool = { workspace = true }
signer = { workspace = true }
indexmap = { workspace = true }
raptorq = { workspace = true }
crossbeam-channel = { workspace = true }

[dev-dependencies]
reqwest = { workspace = true }
