[package]
name = "job_scheduler"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
num_cpus = { workspace = true }
once_cell = { workspace = true }
primitives = { workspace = true }
job_pool = { workspace = true }
vrrb_core = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
