[package]
name = "signer"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
hbbft = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
primitives = { workspace = true }
tokio = { workspace = true }
vrrb_core = { workspace = true }
vrrb_config = { workspace = true }
uuid = { workspace = true }
secp256k1 = { workspace = true }
sha2 = { workspace = true }
