[package]
name = "signer"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
doctest = false

[dependencies]
hbbft = { workspace = true }
primitives = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
vrrb_config = { workspace = true }
vrrb_core = { workspace = true }
