[package]
name = "vrrb_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

secp256k1 = "0.24.0"
vrf = "0.2.4"
