[package]
name = "vrrb_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD

secp256k1 = "0.24.0"
vrf = "0.2.4"
=======
secp256k1 = {version = "0.24.0", features = ["rand"]}
vrf = "0.2.4"
rand_chacha = "0.3.1"
hex = "0.4.3"
rand = "0.8.5"
rand_core = "0.6.3"
parity-wordlist = "1.3.1"
>>>>>>> 037cdeef0eb367e2419d973d8187957b84047113
