[package]
name = "vrrb_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

secp256k1 = {version = "0.24.0", features = ["rand"]}
vrf = "0.2.4"
rand_chacha = "0.3.1"
hex = "0.4.3"
rand = "*"

