[package]
name = "validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
state = { path = "../state" }
mempool = { path = "../mempool" }
left-right = "0.11.5"
lr_trie = { path = "../lr_trie" }
patriecia = { git = "https://github.com/vrrb-io/patriecia" }
sha256 = "1.0.2"
bytebuffer = "0.2.1"
blake3 = "0.3.8"
bincode = "1.3.3"
lrdb = { path = "../lrdb" }
vrrb_core = { path = "../vrrb_core" }

[dev-dependencies]
rand = "0.8.5"
