[package]
name = "validator"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true }
hbbft = { workspace = true }
integral-db = { workspace = true }
left-right = "0.11"
mempool = { workspace = true }
patriecia = { workspace = true }
primitives = { workspace = true }
rayon = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
storage = { workspace = true }
telemetry = { workspace = true }
thiserror = { workspace = true }
vrrb_core = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
