[package]
name = "mempool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evmap = "10.0.2"
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
txn = { path="../txn"}
state = { path="../state"}
left-right = "0.11.5"
threadpool = "1.8.1"
indexmap = "1.9.1"
fxhash = "0.2.1"
blake3 = "0.3.8"
secp256k1 = {version = "0.24.0", features = ["rand"]}
sha256 = "1.0.2"
bytebuffer = "0.2.1"
ecdsa = "0.14.4"
