[package]
name = "mempool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evmap = "10.0.2"
serde_json = "1.0.64"
serde = { version = "1.0.101", features = ["derive"] }
vrrb_core = { path = "../vrrb_core" }
state = { path = "../state" }
left-right = "0.11.5"
indexmap = "1.9.1"
fxhash = "0.2.1"
sha256 = "1.0.2"
bytebuffer = "0.2.1"
ritelinked = { version = "0.3.2", features = ['serde'] }
