[package]
name = "mempool"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true }
vrrb_core = { workspace = true }
primitives = { workspace = true }
left-right = "0.11"
indexmap = { workspace = true }
fxhash = "0.2"
ritelinked = { workspace = true }
chrono = {workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
secp256k1 = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
telemetry = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
