[package]
name = "web3_pkg"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[[example]]
name = "web3-pkg"
path = "../../examples/web3-pkg.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_builder = { workspace = true }
futures = { version = "0.3", features = ["thread-pool"] }
ipfs-api-backend-hyper = { version = "0.6" ,features = ["with-send-sync"] }
ipfs-api = { version ="0.17" }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
