[package]
name = "utils"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bincode = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
