[package]
name = "vrrb_rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
serde = "1.0.147"
serde_json = "1.0.87"
vrrb_core = { path = "../vrrb_core" }
telemetry = { path = "../telemetry" }
tracing = "0.1.37"
axum = "0.5.17"
axum-server = { version = "0.4.4", features = ["tls-rustls"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace"] }
hyper = { version = "0.14.23", features = ["full"] }
