[package]
name = "vrrb_rpc"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
vrrb_core = { workspace = true }
telemetry = { workspace = true }
primitives = { workspace = true }
storage = { workspace = true }
mempool = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
axum-server = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
hyper = { workspace = true }
jsonrpsee = "0.16.2"
async-trait = { workspace = true }
anyhow = { workspace = true }
secp256k1 = { workspace = true }
tokio-rustls = "0.23.4"
rcgen = "0.10.0"
hyper-rustls = { version = "0.23.2", features = ["http1", "http2", "tls12"] }
rustls-pemfile = "1.0.2"
futures-util = "0.3.27"
hyper-reverse-proxy = "0.5.1"

[dev-dependencies]
hyper = { workspace = true }
reqwest = { workspace = true }
