[package]
name = "vrrb_vrf"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hex = { workspace = true }
parity-wordlist = "1.3"
primitives = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rand_core = "0.6"
vrf = "0.2"

[dev-dependencies]
vrrb_core = { workspace = true }
