[package]
name = "vrrb_vrf"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
vrf = "0.2.4"
rand_chacha = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
rand_core = "0.6.3"
parity-wordlist = "1.3.1"
primitives = { workspace = true }

[dev-dependencies]
vrrb_core = { workspace = true }
