[package]
name = "state_trie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_merkle = { git = "https://github.com/vrrb-io/rs-merkle", branch = "master" }
