[package]
name = "metric_exporter"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hyper = { workspace = true }
hyper-rustls = { version = "0.24", features = ["acceptor"] }
platform = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
rustls = "0.21"
rustls-pemfile = "1.0"
telemetry = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "metrics_example"
path = "src/examples/metrics_example.rs"
