[package]
name = "metric_exporter"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
hyper = { workspace = true }
platform = { workspace = true }
prometheus = { workspace = true }
hyper-rustls = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
telemetry = { workspace = true }
tokio-util = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[[example]]
name = "metrics_example"
path = "src/examples/metrics_example.rs"
