[package]
name = "metric_exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.27", features = ["full"] }
tokio = { workspace = true }
thiserror = { workspace = true}
log = "0.4.20"
async-trait = "0.1.74"
rand = "0.8.5"
platform = { workspace = true}
prometheus = { workspace = true}


[[example]]
name = "metrics_example"
path = "src/examples/metrics_example.rs"