[package]
name = "vrrb_config"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
derive_builder = { workspace = true }
hbbft = { workspace = true }
primitives = { workspace = true }
rand = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
vrrb_core = { workspace = true }
