[package]
name = "vrrb_config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
primitives = { path = "../primitives" }
hbbft = { git = "https://github.com/vrrb-io/hbbft", branch = "master" }
rand = "0.8.5"
secp256k1 = { version = "0.24.0", features = ["global-context", "rand"] }
