[package]
name = "telemetry"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
log = "0.4"
primitives = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "registry",
  "env-filter",
  "tracing-log",
  "json",
] }
