[package]
name = "miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ritelinked = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
sha256 = { workspace = true }
patriecia = { workspace = true }
primitives = { workspace = true }
vrrb_core = { workspace = true }
reward = { workspace = true }
state = { workspace = true }
block = { workspace = true }
mempool = { workspace = true }
thiserror = { workspace = true }
utils = { workspace = true }
