[package]
name = "job_pool"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
once_cell = { workspace = true }
waker-fn = { workspace = true }
uuid = { workspace = true }
concurrent-queue = { workspace = true }
thiserror = { workspace = true }
vrrb_core = { workspace = true }
