[package]
name = "job_pool"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
crossbeam-channel = { workspace = true }
once_cell = { workspace = true }
waker-fn = "1.1"
uuid = { workspace = true }
concurrent-queue = "2.0"
thiserror = { workspace = true }
