[package]
name = "syncing"
version = "0.1.0"
edition = "2021"

[dependencies]
telemetry = { path = "../telemetry" }
tokio = { version = "1.0", features = ["io-util", "io-std", "macros", "rt", "rt-multi-thread", "sync", "fs", "net", "time"] }
once_cell = "1.5"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.3"
clap = { version = "4.0", features = ["derive"] }
left-right = "0.11.5"
bs58 = "0.4.0"
async-std = "1.0.1"
futures = {version="0.3.1", features= ["thread-pool"]}
futures-timer = "0.4.0"
err-derive = "0.3.0"
uuid = {version = "1.2.1", features = ["v4"]}
chrono = "0.4.22"
serde_derive = "1.0.147"
config = "0.13.1"
udt = "0.2"
queues = "1.1.0"
rcrefcell = "1.0.7"
