[package]
name = "node_cli"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.19", features = ["derive"] }
telemetry = { path = "../../telemetry" }
thiserror = "1.0.33"
tokio = { version = "1.21.0", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = [
    "fmt",
    "registry",
    "env-filter",
    "tracing-log",
    "json",
] }
