[package]
name = "message"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commands = { path = "../../commands" }
tokio = { version = "1.12.0", features = ["full"] }
messages = { path = "../../messages" }
tokio-test = "0.4.2"
log = "0.4.14"
udp2p = { git = "https://github.com/ASmithOWL/udp2p", branch = "main" }