[package]
name = "compute_runtime"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
bitmask-enum = { workspace = true }
derive_builder = { workspace = true }
oci-spec = "0.6"
telemetry = { workspace = true }
uds = "0.4"

[dev-dependencies]
env_logger = "0.10"
mktemp = "0.5"
