[package]
name = "compute_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmask-enum = { workspace = true }
anyhow = { workspace = true }
mktemp = { workspace = true }
oci-spec = { workspace = true }
telemetry = { workspace = true }
derive_builder = { workspace = true }
env_logger = { workspace = true }
uds = { workspace = true }
