[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# hex = "*"
hex = { workspace = true }
sha256 = { workspace = true }
ritelinked = { workspace = true }
serde_json = { workspace = true }
udp2p = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
raptorq = { workspace = true }
crossbeam-channel = { workspace = true }
serde = { workspace = true }
qp2p = { workspace = true }
bytes = { workspace = true }
telemetry = { workspace = true }
tracing = { workspace = true }
vrrb_core = { workspace = true }
primitives = { workspace = true }
block = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
events = { workspace = true }
theater = { workspace = true }
chrono = { workspace = true }
