[package]
name = "network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "*"
sha256 = "1.0.2"
ritelinked = { version = "0.3.2", features = ['serde'] }
serde_json = "1.0.64"
log = "0.4.14"
udp2p = { git = "https://github.com/ASmithOWL/udp2p" }
tokio = { version = "1.21.0", features = ["full"] }
futures = { version = "0.3.24", features = ["thread-pool"] }
rand = "0.8.5"
raptorq = "1.7.0"
crossbeam-channel = "0.5.6"
serde = { version = "1.0.144", features = ["derive"] }
qp2p = "0.30.0"
bytes = { version = "1.2.1", features = ["serde"] }
telemetry = { path = "../telemetry" }
vrrb_core = { path = "../vrrb_core" }
primitives = { path = "../primitives" }
thiserror = "1.0.33"
uuid = { version = "1.2.1", features = ["v4", "serde"] }
