on: [pull_request]

name: cargo

env:
  CARGO_TERM_COLOR: always

concurrency:
  cancel-in-progress: true

jobs:
  # tests all crates in parallel
  test-block:
    name: test block
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/block/Cargo.toml

  test-blockchain:
    name: test blockchain
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/blockchain/Cargo.toml

  test-cli:
    name: test cli
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/cli/Cargo.toml

  test-consensus:
    name: test consensus
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/consensus/Cargo.toml

  test-events:
    name: test events
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/events/Cargo.toml

  test-mempool:
    name: test mempool
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/mempool/Cargo.toml

  test-miner:
    name: test miner
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/miner/Cargo.toml

  test-network:
    name: test network
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/network/Cargo.toml

  test-node:
    name: test node
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/node/Cargo.toml

  test-primitives:
    name: test primitives
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/primitives/Cargo.toml

  test-storage:
    name: test storage
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/storage/Cargo.toml

  test-telemetry:
    name: test telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/telemetry/Cargo.toml

  test-utils:
    name: test utils
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/utils/Cargo.toml

  test-validator:
    name: test validator
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/validator/Cargo.toml

  test-vrrb-config:
    name: test vrrb_config
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_config/Cargo.toml

  test-vrrb-core:
    name: test vrrb_core
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_core/Cargo.toml

  test-vrrb-grpc:
    name: test vrrb_grpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_grpc/Cargo.toml

  test-vrrb-http:
    name: test vrrb_http
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_http/Cargo.toml

  test-vrrb-rpc:
    name: test vrrb_rpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_rpc/Cargo.toml

  test-wallet:
    name: test wallet
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/wallet/Cargo.toml
