on: [pull_request]

name: cargo test

jobs:
  # tests all crates in parallel
  test-block:
    name: crates/block
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/block/Cargo.toml

  test-blockchain:
    name: crates/blockchain
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/blockchain/Cargo.toml

  test-cli:
    name: crates/cli
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/cli/Cargo.toml

  test-consensus:
    name: crates/consensus
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/consensus/Cargo.toml

  test-events:
    name: crates/events
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/events/Cargo.toml

  test-mempool:
    name: crates/mempool
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/mempool/Cargo.toml

  test-miner:
    name: crates/miner
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/miner/Cargo.toml

  test-network:
    name: crates/network
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/network/Cargo.toml

  test-node:
    name: crates/node
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/node/Cargo.toml

  test-primitives:
    name: crates/primitives
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/primitives/Cargo.toml

  test-storage:
    name: crates/storage
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/storage/Cargo.toml

  test-telemetry:
    name: crates/telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/telemetry/Cargo.toml

  test-utils:
    name: crates/utils
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/utils/Cargo.toml

  test-validator:
    name: crates/validator
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/validator/Cargo.toml

  test-vrrb-config:
    name: crates/vrrb_config
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_config/Cargo.toml

  test-vrrb-core:
    name: crates/vrrb_core
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_core/Cargo.toml

  test-vrrb-grpc:
    name: crates/vrrb_grpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_grpc/Cargo.toml

  test-vrrb-http:
    name: crates/vrrb_http
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_http/Cargo.toml

  test-vrrb-rpc:
    name: crates/vrrb_rpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/vrrb_rpc/Cargo.toml

  test-wallet:
    name: crates/wallet
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./crates/wallet/Cargo.toml
