name: cargo
on: [pull_request]
env:
  CARGO_TERM_COLOR: always

jobs:
  # check workspace for warnings & treat them as errors
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  # check if workspace is formatted, and treat unformatted code as errors.
  fmt-check:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dsherret/rust-toolchain-file@v1
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Install taplo-cli
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: taplo-cli
      - name: Run taplo linter
        run: taplo format --check --verbose

  # tests all crates in parallel
  test-block:
    name: test block
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p block

  test-cli:
    name: test cli
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p cli

  test-consensus:
    name: test consensus
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test consensus
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p consensus
      - name: cargo test dkg_engine
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p dkg_engine
      - name: cargo test job_pool
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p job_pool
      - name: cargo test job_scheduler
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p job_scheduler
      - name: cargo test quorum
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p quorum
      - name: cargo test reward
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p reward
      - name: cargo test signer
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p signer
      - name: cargo test vrrb_vrf
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrb_vrf

  test-events:
    name: test events
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p events

  test-mempool:
    name: test mempool
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p mempool

  test-miner:
    name: test miner
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p miner

  test-node:
    name: test node
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p node

  test-primitives:
    name: test primitives
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p primitives

  test-storage:
    name: test storage
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test storage
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p storage
      - name: cargo test vrrbdb
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrbdb
      - name: cargo test storage_utils
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p storage_utils

  test-telemetry:
    name: test telemetry
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p telemetry

  test-utils:
    name: test utils
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p utils

  test-validator:
    name: test validator
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p validator

  test-vrrb-config:
    name: test vrrb_config
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrb_config

  test-vrrb-core:
    name: test vrrb_core
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrb_core

  test-vrrb-http:
    name: test vrrb_http
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrb_http

  test-vrrb-rpc:
    name: test vrrb_rpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p vrrb_rpc

  test-internal-rpc:
    name: test internal_rpc
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p internal_rpc

  test-wallet:
    name: test wallet
    runs-on: ubuntu-latest
    steps:
      - name: Install dev-dependencies
        run: sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p wallet
