[package]
name = "compute_cli"
description = "Verstatus Compute Agent CLI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "versa-compute"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
internal_rpc = { workspace = true }
clap = { workspace = true }
telemetry = { workspace = true }
service_config = { workspace = true }
tokio = { workspace = true }
prometheus = { workspace = true }
hyper = { workspace = true }
rand = { workspace = true }
lazy_static = { workspace = true }
platform = { workspace = true }
