[package]
name = "quorum"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
vrrb_core = { workspace = true }
vrrb_vrf = { workspace = true }
rand_chacha = { workspace = true }
thread_local = "1.1"
thiserror = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
primitives = { workspace = true }
serde = { workspace = true }
ethereum-types = { workspace = true }

[dev-dependencies]
sha256 = { workspace = true }
